-- ============================================================
-- 01_schema.sql  —  EXISTING TABLE STRUCTURE
-- Mirrors production Supabase (shgloxculzfaghlirxxy).
-- Run once on fresh Docker. pg_dump data-only is applied after this.
-- ============================================================

-- Custom ENUM types
CREATE TYPE enable_reminder AS ENUM ('yes', 'no');
CREATE TYPE user_status     AS ENUM ('active', 'inactive', 'on_leave', 'terminated');
CREATE TYPE task_status     AS ENUM ('pending', 'in_progress', 'completed', 'rejected', 'done', 'extend');

-- Sequences used by log tables
CREATE SEQUENCE IF NOT EXISTS log_checklist_id_seq;
CREATE SEQUENCE IF NOT EXISTS log_maintenance_id_seq;

-- --------------------------------------------------------
-- users  (41 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        TIMESTAMPTZ  DEFAULT now(),
  user_name         TEXT,
  password          TEXT,
  email_id          TEXT,
  number            BIGINT       UNIQUE,
  department        TEXT,
  given_by          TEXT,
  role              TEXT,
  status            user_status,
  user_access       TEXT,
  leave_date        TIMESTAMP,
  remark            TEXT,
  leave_end_date    TIMESTAMP,
  employee_id       TEXT,
  last_punch_time   TIMESTAMP,
  last_punch_device TEXT,
  page_access       TEXT,
  system_access     TEXT
);

-- --------------------------------------------------------
-- working_day_calender  (312 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.working_day_calender (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  working_date DATE,
  day          TEXT,
  week_num     INTEGER,
  month        INTEGER
);

-- --------------------------------------------------------
-- unique_checklist  (366 rows in prod)  — task templates
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.unique_checklist (
  task_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT,
  department          TEXT,
  task_description    TEXT,
  task_end_date       TIMESTAMPTZ,
  frequency           TEXT        DEFAULT 'daily',
  require_attachment  TEXT        CHECK (require_attachment = ANY (ARRAY['yes', 'no'])),
  created_at          TIMESTAMPTZ DEFAULT now(),
  given_by            TEXT,
  task_start_date     TIMESTAMPTZ,
  enable_reminder     TEXT        CHECK (enable_reminder = ANY (ARRAY['yes', 'no'])),
  image               TEXT
);

-- --------------------------------------------------------
-- checklist  (56 386 rows in prod)  — generated task instances
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.checklist (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department         TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  enable_reminder    enable_reminder,
  require_attachment enable_reminder,
  frequency          TEXT,
  remark             TEXT,
  status             TEXT,
  image              TEXT,
  admin_done         TEXT,
  delay              INTERVAL,
  planned_date       TEXT,
  created_at         TIMESTAMP   DEFAULT now(),
  task_start_date    TIMESTAMP,
  submission_date    TIMESTAMP,
  next_extend_date   TIMESTAMPTZ,
  sample_image       TEXT,
  modified_at        TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- delegation  (218 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.delegation (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP   DEFAULT now(),
  department         TEXT,
  name               TEXT,
  task_description   TEXT,
  frequency          TEXT,
  remarks            TEXT,
  task_start_date    TIMESTAMP   NOT NULL,
  given_by           TEXT,
  image              TEXT,
  enable_reminder    enable_reminder,
  require_attachment TEXT,
  status             TEXT,
  updated_at         TIMESTAMP,
  planned_date       TIMESTAMP,
  submission_date    TIMESTAMP,
  color_code_for     BIGINT,
  delay              INTERVAL,
  sample_image       TEXT
);

-- --------------------------------------------------------
-- delegation_done  (0 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.delegation_done (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id          BIGINT,
  created_at       TIMESTAMPTZ DEFAULT now(),
  status           task_status,
  next_extend_date TIMESTAMP,
  reason           TEXT,
  image_url        TEXT,
  name             TEXT,
  task_description TEXT,
  given_by         TEXT
);

-- --------------------------------------------------------
-- unique_maintanence  (125 rows in prod)  — maintenance templates
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.unique_maintanence (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_name       TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  task_start_date    TIMESTAMPTZ,
  frequency          TEXT        DEFAULT 'daily',
  enable_reminder    TEXT        CHECK (enable_reminder = ANY (ARRAY['yes', 'no'])),
  require_attachment TEXT        CHECK (require_attachment = ANY (ARRAY['yes', 'no'])),
  created_at         TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- machine_maintenance  (1 480 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.machine_maintenance (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP DEFAULT now(),
  machine_name       TEXT,
  serial_no          TEXT,
  department         TEXT,
  task_description   TEXT,
  frequency          TEXT,
  doer_name          TEXT,
  task_start_date    TIMESTAMP,
  actual_date        TIMESTAMP,
  delay              INTERVAL,
  status             TEXT      DEFAULT 'pending',
  remarks            TEXT,
  image_url          TEXT,
  maintenance_cost   NUMERIC,
  require_attachment TEXT,
  enable_reminder    TEXT,
  sample_image       TEXT,
  machine_type       TEXT,
  given_by           TEXT
);

-- --------------------------------------------------------
-- machines  (27 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.machines (
  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at   TIMESTAMPTZ DEFAULT now(),
  machine_name TEXT        NOT NULL,
  serial_no    TEXT,
  model        TEXT,
  location     TEXT,
  department   TEXT,
  status       TEXT        NOT NULL DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  type         TEXT        DEFAULT ''
);

-- --------------------------------------------------------
-- maintenance_schedules  (165 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.maintenance_schedules (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMPTZ DEFAULT timezone('utc', now()),
  machine_name       TEXT        NOT NULL,
  task_description   TEXT        NOT NULL,
  frequency          TEXT        NOT NULL,
  assigned_to        TEXT,
  department         TEXT,
  require_attachment TEXT,
  enable_reminder    TEXT,
  machine_type       TEXT
);

-- --------------------------------------------------------
-- machine_repair  (250 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.machine_repair (
  task_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          TIMESTAMP DEFAULT now(),
  form_filled_by      TEXT,
  assigned_to         TEXT,
  machine_name        TEXT,
  issue_detail        TEXT,
  part_replaced       TEXT,
  task_start_date     TIMESTAMP,
  actual_date         TIMESTAMP,
  delay               INTERVAL,
  work_done           TEXT,
  photo_url           TEXT,
  status              TEXT      DEFAULT 'pending',
  vendor_name         TEXT,
  bill_copy_url       TEXT,
  bill_amount         NUMERIC,
  remarks             TEXT,
  motor_name          TEXT,
  warranty            TEXT,
  machine_type        TEXT,
  warranty_start_date DATE,
  warranty_end_date   DATE,
  "Work_Done_By"      TEXT,
  "Type_of_Work"      TEXT,
  rate                NUMERIC,
  qty                 NUMERIC,
  purchase_date       DATE
);

-- --------------------------------------------------------
-- machine_motors  (40 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.machine_motors (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     TIMESTAMPTZ DEFAULT now(),
  machine_name   TEXT        NOT NULL,
  motor_name     TEXT        NOT NULL,
  load           TEXT,
  last_work_date TIMESTAMP,
  entry_date     TIMESTAMP
);

-- --------------------------------------------------------
-- repair_machine_types  (9 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.repair_machine_types (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name  TEXT        NOT NULL UNIQUE,
  status     TEXT        DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- repair_machine_names  (152 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.repair_machine_names (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_id      BIGINT      REFERENCES public.repair_machine_types(id),
  machine_name TEXT        NOT NULL,
  status       TEXT        DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  created_at   TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- holidays  (4 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.holidays (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  leave_date DATE        NOT NULL UNIQUE,
  reason     TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- user_permissions  (239 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_permissions (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL REFERENCES public.users(id),
  resource   TEXT        NOT NULL,
  can_read   BOOLEAN     DEFAULT false,
  can_write  BOOLEAN     DEFAULT false,
  can_edit   BOOLEAN     DEFAULT false,
  can_delete BOOLEAN     DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- vendorlist  (69 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vendorlist (
  id              SERIAL PRIMARY KEY,
  "VENDOR CODE"   TEXT,
  "Vendro Name"   TEXT,
  "Contact No"    TEXT,
  "Location"      TEXT,
  "Venodr Type"   TEXT,
  "Parts Name"    TEXT,
  "Work Type"     TEXT,
  "Visiting Card" TEXT,
  "Images If Any" TEXT,
  "FROM LINK"     TEXT,
  "Timestamp"     TIMESTAMPTZ
);

-- --------------------------------------------------------
-- itemdetails  (103 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.itemdetails (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "VENDOR CODE"       TEXT,
  "ITEM NAME"         TEXT,
  "RATE"              TEXT,
  "QTY"               TEXT,
  "UNIT"              TEXT,
  "VENDOR NAME"       TEXT,
  "Timestamp"         TIMESTAMP,
  "DATE OF PURCHASE"  DATE
);

-- --------------------------------------------------------
-- log_checklist  (8 890 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.log_checklist (
  id               BIGINT PRIMARY KEY DEFAULT nextval('log_checklist_id_seq'),
  "checklist id"   TEXT,
  action           TEXT,
  "action done by" TEXT,
  department       TEXT,
  "given by"       TEXT,
  "doer name"      TEXT,
  frequency        TEXT,
  "from date"      DATE,
  "end date"       DATE,
  description      TEXT
);

-- --------------------------------------------------------
-- log_maintenance  (1 344 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.log_maintenance (
  id               BIGINT PRIMARY KEY DEFAULT nextval('log_maintenance_id_seq'),
  maintenance_id   TEXT,
  action           TEXT,
  action_done_by   TEXT,
  machine          TEXT,
  given_by         TEXT,
  doer             TEXT,
  frequency        TEXT,
  from_date        DATE,
  task_description TEXT
);

-- --------------------------------------------------------
-- log_delegation  (9 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.log_delegation (
  id               INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id          VARCHAR,
  action           TEXT,
  action_done_by   VARCHAR,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name             VARCHAR,
  task_description TEXT,
  frequency        VARCHAR
);

-- --------------------------------------------------------
-- backup_checklist  (4 178 rows in prod)  — no PK
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.backup_checklist (
  task_id            BIGINT,
  department         TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  enable_reminder    enable_reminder,
  require_attachment enable_reminder,
  frequency          TEXT,
  remark             TEXT,
  status             TEXT,
  image              TEXT,
  admin_done         TEXT,
  delay              INTERVAL,
  planned_date       TEXT,
  created_at         TIMESTAMP DEFAULT now(),
  task_start_date    TIMESTAMP,
  submission_date    TIMESTAMP,
  next_extend_date   TIMESTAMPTZ,
  sample_image       TEXT
);

-- --------------------------------------------------------
-- backup_machine_maintenance  (2 rows in prod)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.backup_machine_maintenance (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP DEFAULT now(),
  machine_name       TEXT,
  serial_no          TEXT,
  department         TEXT,
  task_description   TEXT,
  frequency          TEXT,
  doer_name          TEXT,
  task_start_date    TIMESTAMP,
  actual_date        TIMESTAMP,
  delay              INTERVAL,
  status             TEXT      DEFAULT 'pending',
  remarks            TEXT,
  image_url          TEXT,
  maintenance_cost   NUMERIC,
  require_attachment TEXT,
  enable_reminder    TEXT,
  sample_image       TEXT,
  machine_type       TEXT
);
