-- ============================================================
-- LOCAL TESTING SQL FILE
-- Project: mis-creator's Project (shgloxculzfaghlirxxy)
-- Generated: 2026-05-05
--
-- HOW TO USE:
--   psql -U postgres -d your_local_db -f schema_and_new_tables.sql
--
-- SECTIONS:
--   A  — Existing table structure (mirror of production)
--   B  — New tables (departments, user links, task migration)
--   C  — Backfill queries (populate new tables from existing strings)
--
-- WARNING: Do NOT run Section A against production — tables already exist.
--          Only Section B (new tables) needs to be applied to production.
-- ============================================================


-- ============================================================
-- SECTION A: EXISTING DATABASE STRUCTURE
-- ============================================================

-- ------------------------------------------------------------
-- Custom ENUM types (must be created before tables that use them)
-- ------------------------------------------------------------
CREATE TYPE enable_reminder AS ENUM ('yes', 'no');
CREATE TYPE user_status     AS ENUM ('active', 'inactive', 'on_leave', 'terminated');
CREATE TYPE task_status     AS ENUM ('pending', 'in_progress', 'completed', 'rejected', 'done', 'extend');

-- Sequences used by log tables
CREATE SEQUENCE log_checklist_id_seq;
CREATE SEQUENCE log_maintenance_id_seq;

-- ------------------------------------------------------------
-- TABLE: users
-- 41 rows. Mixes real users (user_name NOT NULL) and department
-- placeholder rows (user_name NULL, IDs 11-17).
-- ------------------------------------------------------------
CREATE TABLE public.users (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        TIMESTAMPTZ  DEFAULT now(),
  user_name         TEXT,
  password          TEXT,
  email_id          TEXT,
  number            BIGINT       UNIQUE,
  department        TEXT,
  given_by          TEXT,
  role              TEXT,
  status            user_status,
  user_access       TEXT,
  leave_date        TIMESTAMP,
  remark            TEXT,
  leave_end_date    TIMESTAMP,
  employee_id       TEXT,
  last_punch_time   TIMESTAMP,
  last_punch_device TEXT,
  page_access       TEXT,
  system_access     TEXT
);

-- ------------------------------------------------------------
-- TABLE: working_day_calender
-- 312 rows. Drives task generation schedule (Mon-Sat working days).
-- ------------------------------------------------------------
CREATE TABLE public.working_day_calender (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  working_date DATE,
  day          TEXT,
  week_num     INTEGER,
  month        INTEGER
);

-- ------------------------------------------------------------
-- TABLE: unique_checklist
-- 366 rows. Task templates — one row per unique task definition.
-- ------------------------------------------------------------
CREATE TABLE public.unique_checklist (
  task_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT,
  department          TEXT,
  task_description    TEXT,
  task_end_date       TIMESTAMPTZ,
  frequency           TEXT        DEFAULT 'daily',
  require_attachment  TEXT        CHECK (require_attachment = ANY (ARRAY['yes', 'no'])),
  created_at          TIMESTAMPTZ DEFAULT now(),
  given_by            TEXT,
  task_start_date     TIMESTAMPTZ,
  enable_reminder     TEXT        CHECK (enable_reminder = ANY (ARRAY['yes', 'no'])),
  image               TEXT
);

-- ------------------------------------------------------------
-- TABLE: checklist
-- 56,386 rows. Generated task instances — up to 2 years of recurring tasks.
-- name/given_by are plain text (no FK to users).
-- ------------------------------------------------------------
CREATE TABLE public.checklist (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department         TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  enable_reminder    enable_reminder,
  require_attachment enable_reminder,
  frequency          TEXT,
  remark             TEXT,
  status             TEXT,
  image              TEXT,
  admin_done         TEXT,
  delay              INTERVAL,
  planned_date       TEXT,
  created_at         TIMESTAMP   DEFAULT now(),
  task_start_date    TIMESTAMP,
  submission_date    TIMESTAMP,
  next_extend_date   TIMESTAMPTZ,
  sample_image       TEXT,
  modified_at        TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- TABLE: delegation
-- 218 rows. Delegated tasks assigned to specific people.
-- ------------------------------------------------------------
CREATE TABLE public.delegation (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP   DEFAULT now(),
  department         TEXT,
  name               TEXT,
  task_description   TEXT,
  frequency          TEXT,
  remarks            TEXT,
  task_start_date    TIMESTAMP   NOT NULL,
  given_by           TEXT,
  image              TEXT,
  enable_reminder    enable_reminder,
  require_attachment TEXT,
  status             TEXT,
  updated_at         TIMESTAMP,
  planned_date       TIMESTAMP,
  submission_date    TIMESTAMP,
  color_code_for     BIGINT,
  delay              INTERVAL,
  sample_image       TEXT
);

-- ------------------------------------------------------------
-- TABLE: delegation_done
-- 0 rows. Completed delegation records.
-- ------------------------------------------------------------
CREATE TABLE public.delegation_done (
  id               UUID      PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id          BIGINT,
  created_at       TIMESTAMPTZ DEFAULT now(),
  status           task_status,
  next_extend_date TIMESTAMP,
  reason           TEXT,
  image_url        TEXT,
  name             TEXT,
  task_description TEXT,
  given_by         TEXT
);

-- ------------------------------------------------------------
-- TABLE: unique_maintanence  (note: original typo preserved)
-- 125 rows. Maintenance task templates.
-- ------------------------------------------------------------
CREATE TABLE public.unique_maintanence (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_name       TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  task_start_date    TIMESTAMPTZ,
  frequency          TEXT        DEFAULT 'daily',
  enable_reminder    TEXT        CHECK (enable_reminder = ANY (ARRAY['yes', 'no'])),
  require_attachment TEXT        CHECK (require_attachment = ANY (ARRAY['yes', 'no'])),
  created_at         TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- TABLE: machine_maintenance
-- 1,480 rows. Generated maintenance task instances.
-- doer_name is plain text (no FK to users).
-- ------------------------------------------------------------
CREATE TABLE public.machine_maintenance (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP DEFAULT now(),
  machine_name       TEXT,
  serial_no          TEXT,
  department         TEXT,
  task_description   TEXT,
  frequency          TEXT,
  doer_name          TEXT,
  task_start_date    TIMESTAMP,
  actual_date        TIMESTAMP,
  delay              INTERVAL,
  status             TEXT      DEFAULT 'pending',
  remarks            TEXT,
  image_url          TEXT,
  maintenance_cost   NUMERIC,
  require_attachment TEXT,
  enable_reminder    TEXT,
  sample_image       TEXT,
  machine_type       TEXT,
  given_by           TEXT
);

-- ------------------------------------------------------------
-- TABLE: machines
-- 27 rows. Machine master list. RLS enabled in production.
-- ------------------------------------------------------------
CREATE TABLE public.machines (
  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at   TIMESTAMPTZ DEFAULT now(),
  machine_name TEXT        NOT NULL,
  serial_no    TEXT,
  model        TEXT,
  location     TEXT,
  department   TEXT,
  status       TEXT        NOT NULL DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  type         TEXT        DEFAULT ''
);

-- ------------------------------------------------------------
-- TABLE: maintenance_schedules
-- 165 rows. Schedule definitions for maintenance tasks.
-- ------------------------------------------------------------
CREATE TABLE public.maintenance_schedules (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMPTZ DEFAULT timezone('utc', now()),
  machine_name       TEXT        NOT NULL,
  task_description   TEXT        NOT NULL,
  frequency          TEXT        NOT NULL,
  assigned_to        TEXT,
  department         TEXT,
  require_attachment TEXT,
  enable_reminder    TEXT,
  machine_type       TEXT
);

-- ------------------------------------------------------------
-- TABLE: machine_repair
-- 250 rows. Repair / breakdown records.
-- ------------------------------------------------------------
CREATE TABLE public.machine_repair (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP DEFAULT now(),
  form_filled_by     TEXT,
  assigned_to        TEXT,
  machine_name       TEXT,
  issue_detail       TEXT,
  part_replaced      TEXT,
  task_start_date    TIMESTAMP,
  actual_date        TIMESTAMP,
  delay              INTERVAL,
  work_done          TEXT,
  photo_url          TEXT,
  status             TEXT      DEFAULT 'pending',
  vendor_name        TEXT,
  bill_copy_url      TEXT,
  bill_amount        NUMERIC,
  remarks            TEXT,
  motor_name         TEXT,
  warranty           TEXT,
  machine_type       TEXT,
  warranty_start_date DATE,
  warranty_end_date   DATE,
  "Work_Done_By"     TEXT,
  "Type_of_Work"     TEXT,
  rate               NUMERIC,
  qty                NUMERIC,
  purchase_date      DATE
);

-- ------------------------------------------------------------
-- TABLE: machine_motors
-- 40 rows. Motor details per machine.
-- ------------------------------------------------------------
CREATE TABLE public.machine_motors (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     TIMESTAMPTZ DEFAULT now(),
  machine_name   TEXT        NOT NULL,
  motor_name     TEXT        NOT NULL,
  load           TEXT,
  last_work_date TIMESTAMP,
  entry_date     TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: repair_machine_types
-- 9 rows. Machine type categories for repairs.
-- ------------------------------------------------------------
CREATE TABLE public.repair_machine_types (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name  TEXT        NOT NULL UNIQUE,
  status     TEXT        DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- TABLE: repair_machine_names
-- 152 rows. Machine names grouped by type.
-- ------------------------------------------------------------
CREATE TABLE public.repair_machine_names (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_id      BIGINT      REFERENCES public.repair_machine_types(id),
  machine_name TEXT        NOT NULL,
  status       TEXT        DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  created_at   TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- TABLE: holidays
-- 4 rows. Public holiday dates (excluded from task generation).
-- ------------------------------------------------------------
CREATE TABLE public.holidays (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  leave_date DATE        NOT NULL UNIQUE,
  reason     TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- TABLE: user_permissions
-- 239 rows. Per-user, per-resource CRUD permissions.
-- Only table with FK to users in production.
-- ------------------------------------------------------------
CREATE TABLE public.user_permissions (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL REFERENCES public.users(id),
  resource   TEXT        NOT NULL,
  can_read   BOOLEAN     DEFAULT false,
  can_write  BOOLEAN     DEFAULT false,
  can_edit   BOOLEAN     DEFAULT false,
  can_delete BOOLEAN     DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- TABLE: vendorlist
-- 69 rows. Vendor contact and product information.
-- Note: column names preserved exactly as in production (spaces, mixed case).
-- ------------------------------------------------------------
CREATE TABLE public.vendorlist (
  id              SERIAL PRIMARY KEY,
  "VENDOR CODE"   TEXT,
  "Vendro Name"   TEXT,
  "Contact No"    TEXT,
  "Location"      TEXT,
  "Venodr Type"   TEXT,
  "Parts Name"    TEXT,
  "Work Type"     TEXT,
  "Visiting Card" TEXT,
  "Images If Any" TEXT,
  "FROM LINK"     TEXT,
  "Timestamp"     TIMESTAMPTZ
);

-- ------------------------------------------------------------
-- TABLE: itemdetails
-- 103 rows. Item/parts purchase details.
-- ------------------------------------------------------------
CREATE TABLE public.itemdetails (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "VENDOR CODE"       TEXT,
  "ITEM NAME"         TEXT,
  "RATE"              TEXT,
  "QTY"               TEXT,
  "UNIT"              TEXT,
  "VENDOR NAME"       TEXT,
  "Timestamp"         TIMESTAMP,
  "DATE OF PURCHASE"  DATE
);

-- ------------------------------------------------------------
-- TABLE: log_checklist
-- 8,890 rows. Audit log for checklist actions.
-- Note: column names with spaces preserved from production.
-- ------------------------------------------------------------
CREATE TABLE public.log_checklist (
  id               BIGINT PRIMARY KEY DEFAULT nextval('log_checklist_id_seq'),
  "checklist id"   TEXT,
  action           TEXT,
  "action done by" TEXT,
  department       TEXT,
  "given by"       TEXT,
  "doer name"      TEXT,
  frequency        TEXT,
  "from date"      DATE,
  "end date"       DATE,
  description      TEXT
);

-- ------------------------------------------------------------
-- TABLE: log_maintenance
-- 1,344 rows. Audit log for maintenance actions.
-- ------------------------------------------------------------
CREATE TABLE public.log_maintenance (
  id               BIGINT PRIMARY KEY DEFAULT nextval('log_maintenance_id_seq'),
  maintenance_id   TEXT,
  action           TEXT,
  action_done_by   TEXT,
  machine          TEXT,
  given_by         TEXT,
  doer             TEXT,
  frequency        TEXT,
  from_date        DATE,
  task_description TEXT
);

-- ------------------------------------------------------------
-- TABLE: log_delegation
-- 9 rows. Audit log for delegation actions.
-- ------------------------------------------------------------
CREATE TABLE public.log_delegation (
  id              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id         VARCHAR,
  action          TEXT,
  action_done_by  VARCHAR,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name            VARCHAR,
  task_description TEXT,
  frequency       VARCHAR
);

-- ------------------------------------------------------------
-- TABLE: backup_checklist
-- 4,178 rows. Point-in-time backup of checklist data. No PK.
-- ------------------------------------------------------------
CREATE TABLE public.backup_checklist (
  task_id            BIGINT,
  department         TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  enable_reminder    enable_reminder,
  require_attachment enable_reminder,
  frequency          TEXT,
  remark             TEXT,
  status             TEXT,
  image              TEXT,
  admin_done         TEXT,
  delay              INTERVAL,
  planned_date       TEXT,
  created_at         TIMESTAMP DEFAULT now(),
  task_start_date    TIMESTAMP,
  submission_date    TIMESTAMP,
  next_extend_date   TIMESTAMPTZ,
  sample_image       TEXT
);

-- ------------------------------------------------------------
-- TABLE: backup_machine_maintenance
-- 2 rows. Point-in-time backup of machine_maintenance.
-- ------------------------------------------------------------
CREATE TABLE public.backup_machine_maintenance (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP DEFAULT now(),
  machine_name       TEXT,
  serial_no          TEXT,
  department         TEXT,
  task_description   TEXT,
  frequency          TEXT,
  doer_name          TEXT,
  task_start_date    TIMESTAMP,
  actual_date        TIMESTAMP,
  delay              INTERVAL,
  status             TEXT      DEFAULT 'pending',
  remarks            TEXT,
  image_url          TEXT,
  maintenance_cost   NUMERIC,
  require_attachment TEXT,
  enable_reminder    TEXT,
  sample_image       TEXT,
  machine_type       TEXT
);


-- ============================================================
-- SECTION B: NEW TABLES
-- These are ADDITIVE — they do not touch any existing table.
-- Apply only these to production once tested locally.
-- ============================================================

-- ------------------------------------------------------------
-- NEW TABLE: departments
-- Master list of departments.
-- Replaces the 7 NULL-user_name placeholder rows in users (IDs 11-17).
-- Existing users.department and users.user_access (text) columns are kept
-- as-is for now; this table will be linked via user_departments below.
-- ------------------------------------------------------------
CREATE TABLE public.departments (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  dept_name   TEXT        NOT NULL UNIQUE,
  description TEXT,
  is_active   BOOLEAN     DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now()
);

-- Seed with departments found in existing data
INSERT INTO public.departments (dept_name) VALUES
  ('Production'),
  ('Quality'),
  ('Maintenance'),
  ('Store'),
  ('HR'),
  ('Admin'),
  ('Finance'),
  ('IT'),
  ('Purchase'),
  ('Safety');

-- ------------------------------------------------------------
-- NEW TABLE: user_departments
-- Junction table: one user can belong to multiple departments.
-- is_primary = true marks the user's main department for display.
-- ------------------------------------------------------------
CREATE TABLE public.user_departments (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  dept_id    BIGINT      NOT NULL REFERENCES public.departments(id) ON DELETE CASCADE,
  is_primary BOOLEAN     DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, dept_id)
);

CREATE INDEX idx_user_departments_user_id ON public.user_departments(user_id);
CREATE INDEX idx_user_departments_dept_id ON public.user_departments(dept_id);

-- ------------------------------------------------------------
-- NEW TABLE: task_migration_log
-- Audit trail for task reassignment when a user leaves or transfers.
-- UI feature: "Migrate Tasks" — admin selects from_user → to_user,
-- all pending checklist/maintenance tasks move to new assignee.
-- ------------------------------------------------------------
CREATE TABLE public.task_migration_log (
  id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  migrated_at    TIMESTAMPTZ DEFAULT now(),
  migrated_by    TEXT        NOT NULL,
  from_user_id   BIGINT      REFERENCES public.users(id) ON DELETE SET NULL,
  to_user_id     BIGINT      REFERENCES public.users(id) ON DELETE SET NULL,
  from_user_name TEXT        NOT NULL,
  to_user_name   TEXT        NOT NULL,
  task_type      TEXT        NOT NULL CHECK (task_type IN ('checklist', 'maintenance', 'delegation')),
  tasks_migrated INTEGER     NOT NULL DEFAULT 0,
  reason         TEXT,
  task_ids       TEXT
);

CREATE INDEX idx_task_migration_from_user ON public.task_migration_log(from_user_id);
CREATE INDEX idx_task_migration_to_user   ON public.task_migration_log(to_user_id);
CREATE INDEX idx_task_migration_at        ON public.task_migration_log(migrated_at DESC);

-- ------------------------------------------------------------
-- NEW TABLE: checklist_user_links
-- Bridge table linking generated checklist rows to the users table.
-- Does NOT modify or alter the existing checklist table.
--
-- Columns:
--   assignee_user_id   — who the task is assigned to (FK → users)
--   created_by_user_id — which admin assigned it    (FK → users)
--   source_unique_id   — which template it came from (FK → unique_checklist)
-- ------------------------------------------------------------
CREATE TABLE public.checklist_user_links (
  id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id             BIGINT      NOT NULL REFERENCES public.checklist(task_id) ON DELETE CASCADE,
  assignee_user_id    BIGINT      REFERENCES public.users(id)            ON DELETE SET NULL,
  created_by_user_id  BIGINT      REFERENCES public.users(id)            ON DELETE SET NULL,
  source_unique_id    BIGINT      REFERENCES public.unique_checklist(task_id) ON DELETE SET NULL,
  linked_at           TIMESTAMPTZ DEFAULT now(),
  UNIQUE (task_id)
);

CREATE INDEX idx_checklist_links_task_id   ON public.checklist_user_links(task_id);
CREATE INDEX idx_checklist_links_assignee  ON public.checklist_user_links(assignee_user_id);
CREATE INDEX idx_checklist_links_creator   ON public.checklist_user_links(created_by_user_id);
CREATE INDEX idx_checklist_links_source    ON public.checklist_user_links(source_unique_id);

-- ------------------------------------------------------------
-- NEW TABLE: maintenance_user_links
-- Same bridge pattern for machine_maintenance rows.
-- Does NOT modify or alter the existing machine_maintenance table.
-- ------------------------------------------------------------
CREATE TABLE public.maintenance_user_links (
  id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id             BIGINT      NOT NULL REFERENCES public.machine_maintenance(task_id) ON DELETE CASCADE,
  assignee_user_id    BIGINT      REFERENCES public.users(id)               ON DELETE SET NULL,
  created_by_user_id  BIGINT      REFERENCES public.users(id)               ON DELETE SET NULL,
  source_unique_id    BIGINT      REFERENCES public.unique_maintanence(task_id) ON DELETE SET NULL,
  linked_at           TIMESTAMPTZ DEFAULT now(),
  UNIQUE (task_id)
);

CREATE INDEX idx_maintenance_links_task_id   ON public.maintenance_user_links(task_id);
CREATE INDEX idx_maintenance_links_assignee  ON public.maintenance_user_links(assignee_user_id);
CREATE INDEX idx_maintenance_links_creator   ON public.maintenance_user_links(created_by_user_id);
CREATE INDEX idx_maintenance_links_source    ON public.maintenance_user_links(source_unique_id);


-- ============================================================
-- SECTION C: BACKFILL QUERIES
-- Run after Section B tables are created.
-- Populates link tables from existing plain-text string data.
-- Best-effort: rows with no name match will remain unlinked (NULL FKs).
-- ============================================================

-- ------------------------------------------------------------
-- C1. Populate checklist_user_links from checklist.name → users.user_name
-- Inserts one link row per checklist task where name matches a user.
-- ------------------------------------------------------------
INSERT INTO public.checklist_user_links (task_id, assignee_user_id)
SELECT c.task_id, u.id
FROM   public.checklist c
JOIN   public.users u
       ON LOWER(TRIM(c.name)) = LOWER(TRIM(u.user_name))
WHERE  u.user_name IS NOT NULL
ON CONFLICT (task_id) DO UPDATE
  SET assignee_user_id = EXCLUDED.assignee_user_id;

-- ------------------------------------------------------------
-- C2. Backfill source_unique_id on existing link rows
-- Matches by task_description + name (best approximation without a stored FK).
-- ------------------------------------------------------------
UPDATE public.checklist_user_links cl
SET    source_unique_id = uc.task_id
FROM   public.checklist c
JOIN   public.unique_checklist uc
       ON  LOWER(TRIM(c.task_description)) = LOWER(TRIM(uc.task_description))
       AND LOWER(TRIM(c.name))             = LOWER(TRIM(uc.name))
WHERE  cl.task_id         = c.task_id
  AND  cl.source_unique_id IS NULL;

-- ------------------------------------------------------------
-- C3. Populate maintenance_user_links from machine_maintenance.doer_name → users.user_name
-- ------------------------------------------------------------
INSERT INTO public.maintenance_user_links (task_id, assignee_user_id)
SELECT m.task_id, u.id
FROM   public.machine_maintenance m
JOIN   public.users u
       ON LOWER(TRIM(m.doer_name)) = LOWER(TRIM(u.user_name))
WHERE  u.user_name IS NOT NULL
ON CONFLICT (task_id) DO UPDATE
  SET assignee_user_id = EXCLUDED.assignee_user_id;

-- ------------------------------------------------------------
-- C4. Backfill source_unique_id on maintenance link rows
-- ------------------------------------------------------------
UPDATE public.maintenance_user_links ml
SET    source_unique_id = um.task_id
FROM   public.machine_maintenance m
JOIN   public.unique_maintanence um
       ON  LOWER(TRIM(m.task_description)) = LOWER(TRIM(um.task_description))
       AND LOWER(TRIM(m.doer_name))        = LOWER(TRIM(um.name))
WHERE  ml.task_id         = m.task_id
  AND  ml.source_unique_id IS NULL;

-- ------------------------------------------------------------
-- C5. Populate user_departments from users.user_access (text → FK)
-- users.user_access holds department name as a plain string.
-- This seeds the junction table from that text field.
-- ------------------------------------------------------------
INSERT INTO public.user_departments (user_id, dept_id, is_primary)
SELECT u.id, d.id, true
FROM   public.users u
JOIN   public.departments d
       ON LOWER(TRIM(u.user_access)) = LOWER(TRIM(d.dept_name))
WHERE  u.user_name   IS NOT NULL
  AND  u.user_access IS NOT NULL
ON CONFLICT (user_id, dept_id) DO NOTHING;


-- ============================================================
-- VERIFICATION QUERIES
-- Run these after applying all sections to check results.
-- ============================================================

-- How many checklist tasks have a linked user?
-- SELECT COUNT(*) AS linked, (SELECT COUNT(*) FROM checklist WHERE name IS NOT NULL) AS total
-- FROM checklist_user_links WHERE assignee_user_id IS NOT NULL;

-- How many maintenance tasks have a linked user?
-- SELECT COUNT(*) AS linked, (SELECT COUNT(*) FROM machine_maintenance WHERE doer_name IS NOT NULL) AS total
-- FROM maintenance_user_links WHERE assignee_user_id IS NOT NULL;

-- How many checklist tasks have a linked template?
-- SELECT COUNT(*) FROM checklist_user_links WHERE source_unique_id IS NOT NULL;

-- Check user_departments seeding
-- SELECT u.user_name, d.dept_name, ud.is_primary
-- FROM user_departments ud
-- JOIN users u ON u.id = ud.user_id
-- JOIN departments d ON d.id = ud.dept_id
-- ORDER BY u.user_name;
