-- ============================================================
-- test_supabase_schema.sql
-- Paste this into your TEST Supabase project → SQL Editor → Run
--
-- Creates all tables (existing + new) in the correct order.
-- Run this once on a fresh Supabase project to match production.
-- ============================================================


-- ============================================================
-- STEP 1: Custom ENUM types
-- ============================================================
CREATE TYPE enable_reminder AS ENUM ('yes', 'no');
CREATE TYPE user_status     AS ENUM ('active', 'inactive', 'on_leave', 'terminated');
CREATE TYPE task_status     AS ENUM ('pending', 'in_progress', 'completed', 'rejected', 'done', 'extend');


-- ============================================================
-- STEP 2: Sequences (used by log tables)
-- ============================================================
CREATE SEQUENCE IF NOT EXISTS log_checklist_id_seq;
CREATE SEQUENCE IF NOT EXISTS log_maintenance_id_seq;


-- ============================================================
-- STEP 3: Core tables (in FK dependency order)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.users (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        TIMESTAMPTZ  DEFAULT now(),
  user_name         TEXT,
  password          TEXT,
  email_id          TEXT,
  number            BIGINT       UNIQUE,
  department        TEXT,
  given_by          TEXT,
  role              TEXT,
  status            user_status,
  user_access       TEXT,
  leave_date        TIMESTAMP,
  remark            TEXT,
  leave_end_date    TIMESTAMP,
  employee_id       TEXT,
  last_punch_time   TIMESTAMP,
  last_punch_device TEXT,
  page_access       TEXT,
  system_access     TEXT
);

CREATE TABLE IF NOT EXISTS public.working_day_calender (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  working_date DATE,
  day          TEXT,
  week_num     INTEGER,
  month        INTEGER
);

CREATE TABLE IF NOT EXISTS public.unique_checklist (
  task_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT,
  department          TEXT,
  task_description    TEXT,
  task_end_date       TIMESTAMPTZ,
  frequency           TEXT        DEFAULT 'daily',
  require_attachment  TEXT        CHECK (require_attachment = ANY (ARRAY['yes', 'no'])),
  created_at          TIMESTAMPTZ DEFAULT now(),
  given_by            TEXT,
  task_start_date     TIMESTAMPTZ,
  enable_reminder     TEXT        CHECK (enable_reminder = ANY (ARRAY['yes', 'no'])),
  image               TEXT
);

CREATE TABLE IF NOT EXISTS public.checklist (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department         TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  enable_reminder    enable_reminder,
  require_attachment enable_reminder,
  frequency          TEXT,
  remark             TEXT,
  status             TEXT,
  image              TEXT,
  admin_done         TEXT,
  delay              INTERVAL,
  planned_date       TEXT,
  created_at         TIMESTAMP   DEFAULT now(),
  task_start_date    TIMESTAMP,
  submission_date    TIMESTAMP,
  next_extend_date   TIMESTAMPTZ,
  sample_image       TEXT,
  modified_at        TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.delegation (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP   DEFAULT now(),
  department         TEXT,
  name               TEXT,
  task_description   TEXT,
  frequency          TEXT,
  remarks            TEXT,
  task_start_date    TIMESTAMP   NOT NULL,
  given_by           TEXT,
  image              TEXT,
  enable_reminder    enable_reminder,
  require_attachment TEXT,
  status             TEXT,
  updated_at         TIMESTAMP,
  planned_date       TIMESTAMP,
  submission_date    TIMESTAMP,
  color_code_for     BIGINT,
  delay              INTERVAL,
  sample_image       TEXT
);

CREATE TABLE IF NOT EXISTS public.delegation_done (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id          BIGINT,
  created_at       TIMESTAMPTZ DEFAULT now(),
  status           task_status,
  next_extend_date TIMESTAMP,
  reason           TEXT,
  image_url        TEXT,
  name             TEXT,
  task_description TEXT,
  given_by         TEXT
);

CREATE TABLE IF NOT EXISTS public.unique_maintanence (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_name       TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  task_start_date    TIMESTAMPTZ,
  frequency          TEXT        DEFAULT 'daily',
  enable_reminder    TEXT        CHECK (enable_reminder = ANY (ARRAY['yes', 'no'])),
  require_attachment TEXT        CHECK (require_attachment = ANY (ARRAY['yes', 'no'])),
  created_at         TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.machine_maintenance (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP DEFAULT now(),
  machine_name       TEXT,
  serial_no          TEXT,
  department         TEXT,
  task_description   TEXT,
  frequency          TEXT,
  doer_name          TEXT,
  task_start_date    TIMESTAMP,
  actual_date        TIMESTAMP,
  delay              INTERVAL,
  status             TEXT      DEFAULT 'pending',
  remarks            TEXT,
  image_url          TEXT,
  maintenance_cost   NUMERIC,
  require_attachment TEXT,
  enable_reminder    TEXT,
  sample_image       TEXT,
  machine_type       TEXT,
  given_by           TEXT
);

CREATE TABLE IF NOT EXISTS public.machines (
  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at   TIMESTAMPTZ DEFAULT now(),
  machine_name TEXT        NOT NULL,
  serial_no    TEXT,
  model        TEXT,
  location     TEXT,
  department   TEXT,
  status       TEXT        NOT NULL DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  type         TEXT        DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.maintenance_schedules (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMPTZ DEFAULT timezone('utc', now()),
  machine_name       TEXT        NOT NULL,
  task_description   TEXT        NOT NULL,
  frequency          TEXT        NOT NULL,
  assigned_to        TEXT,
  department         TEXT,
  require_attachment TEXT,
  enable_reminder    TEXT,
  machine_type       TEXT
);

CREATE TABLE IF NOT EXISTS public.machine_repair (
  task_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          TIMESTAMP DEFAULT now(),
  form_filled_by      TEXT,
  assigned_to         TEXT,
  machine_name        TEXT,
  issue_detail        TEXT,
  part_replaced       TEXT,
  task_start_date     TIMESTAMP,
  actual_date         TIMESTAMP,
  delay               INTERVAL,
  work_done           TEXT,
  photo_url           TEXT,
  status              TEXT      DEFAULT 'pending',
  vendor_name         TEXT,
  bill_copy_url       TEXT,
  bill_amount         NUMERIC,
  remarks             TEXT,
  motor_name          TEXT,
  warranty            TEXT,
  machine_type        TEXT,
  warranty_start_date DATE,
  warranty_end_date   DATE,
  "Work_Done_By"      TEXT,
  "Type_of_Work"      TEXT,
  rate                NUMERIC,
  qty                 NUMERIC,
  purchase_date       DATE
);

CREATE TABLE IF NOT EXISTS public.machine_motors (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     TIMESTAMPTZ DEFAULT now(),
  machine_name   TEXT        NOT NULL,
  motor_name     TEXT        NOT NULL,
  load           TEXT,
  last_work_date TIMESTAMP,
  entry_date     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.repair_machine_types (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name  TEXT        NOT NULL UNIQUE,
  status     TEXT        DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.repair_machine_names (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_id      BIGINT      REFERENCES public.repair_machine_types(id),
  machine_name TEXT        NOT NULL,
  status       TEXT        DEFAULT 'active' CHECK (status = ANY (ARRAY['active', 'inactive'])),
  created_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.holidays (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  leave_date DATE        NOT NULL UNIQUE,
  reason     TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_permissions (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL REFERENCES public.users(id),
  resource   TEXT        NOT NULL,
  can_read   BOOLEAN     DEFAULT false,
  can_write  BOOLEAN     DEFAULT false,
  can_edit   BOOLEAN     DEFAULT false,
  can_delete BOOLEAN     DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vendorlist (
  id              SERIAL PRIMARY KEY,
  "VENDOR CODE"   TEXT,
  "Vendro Name"   TEXT,
  "Contact No"    TEXT,
  "Location"      TEXT,
  "Venodr Type"   TEXT,
  "Parts Name"    TEXT,
  "Work Type"     TEXT,
  "Visiting Card" TEXT,
  "Images If Any" TEXT,
  "FROM LINK"     TEXT,
  "Timestamp"     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.itemdetails (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "VENDOR CODE"       TEXT,
  "ITEM NAME"         TEXT,
  "RATE"              TEXT,
  "QTY"               TEXT,
  "UNIT"              TEXT,
  "VENDOR NAME"       TEXT,
  "Timestamp"         TIMESTAMP,
  "DATE OF PURCHASE"  DATE
);

CREATE TABLE IF NOT EXISTS public.log_checklist (
  id               BIGINT PRIMARY KEY DEFAULT nextval('log_checklist_id_seq'),
  "checklist id"   TEXT,
  action           TEXT,
  "action done by" TEXT,
  department       TEXT,
  "given by"       TEXT,
  "doer name"      TEXT,
  frequency        TEXT,
  "from date"      DATE,
  "end date"       DATE,
  description      TEXT
);

CREATE TABLE IF NOT EXISTS public.log_maintenance (
  id               BIGINT PRIMARY KEY DEFAULT nextval('log_maintenance_id_seq'),
  maintenance_id   TEXT,
  action           TEXT,
  action_done_by   TEXT,
  machine          TEXT,
  given_by         TEXT,
  doer             TEXT,
  frequency        TEXT,
  from_date        DATE,
  task_description TEXT
);

CREATE TABLE IF NOT EXISTS public.log_delegation (
  id               INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id          VARCHAR,
  action           TEXT,
  action_done_by   VARCHAR,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name             VARCHAR,
  task_description TEXT,
  frequency        VARCHAR
);

CREATE TABLE IF NOT EXISTS public.backup_checklist (
  task_id            BIGINT,
  department         TEXT,
  given_by           TEXT,
  name               TEXT,
  task_description   TEXT,
  enable_reminder    enable_reminder,
  require_attachment enable_reminder,
  frequency          TEXT,
  remark             TEXT,
  status             TEXT,
  image              TEXT,
  admin_done         TEXT,
  delay              INTERVAL,
  planned_date       TEXT,
  created_at         TIMESTAMP DEFAULT now(),
  task_start_date    TIMESTAMP,
  submission_date    TIMESTAMP,
  next_extend_date   TIMESTAMPTZ,
  sample_image       TEXT
);

CREATE TABLE IF NOT EXISTS public.backup_machine_maintenance (
  task_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         TIMESTAMP DEFAULT now(),
  machine_name       TEXT,
  serial_no          TEXT,
  department         TEXT,
  task_description   TEXT,
  frequency          TEXT,
  doer_name          TEXT,
  task_start_date    TIMESTAMP,
  actual_date        TIMESTAMP,
  delay              INTERVAL,
  status             TEXT      DEFAULT 'pending',
  remarks            TEXT,
  image_url          TEXT,
  maintenance_cost   NUMERIC,
  require_attachment TEXT,
  enable_reminder    TEXT,
  sample_image       TEXT,
  machine_type       TEXT
);


-- ============================================================
-- STEP 4: New tables (departments, user links, migration log)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.departments (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  dept_name   TEXT        NOT NULL UNIQUE,
  description TEXT,
  is_active   BOOLEAN     DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now()
);

INSERT INTO public.departments (dept_name) VALUES
  ('Production'),('Quality'),('Maintenance'),('Store'),('HR'),
  ('Admin'),('Finance'),('IT'),('Purchase'),('Safety')
ON CONFLICT (dept_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.user_departments (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  dept_id    BIGINT      NOT NULL REFERENCES public.departments(id) ON DELETE CASCADE,
  is_primary BOOLEAN     DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, dept_id)
);

CREATE INDEX IF NOT EXISTS idx_user_departments_user_id ON public.user_departments(user_id);
CREATE INDEX IF NOT EXISTS idx_user_departments_dept_id ON public.user_departments(dept_id);

CREATE TABLE IF NOT EXISTS public.task_migration_log (
  id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  migrated_at    TIMESTAMPTZ DEFAULT now(),
  migrated_by    TEXT        NOT NULL,
  from_user_id   BIGINT      REFERENCES public.users(id) ON DELETE SET NULL,
  to_user_id     BIGINT      REFERENCES public.users(id) ON DELETE SET NULL,
  from_user_name TEXT        NOT NULL,
  to_user_name   TEXT        NOT NULL,
  task_type      TEXT        NOT NULL CHECK (task_type IN ('checklist', 'maintenance', 'delegation')),
  tasks_migrated INTEGER     NOT NULL DEFAULT 0,
  reason         TEXT,
  task_ids       TEXT
);

CREATE INDEX IF NOT EXISTS idx_task_migration_from_user ON public.task_migration_log(from_user_id);
CREATE INDEX IF NOT EXISTS idx_task_migration_to_user   ON public.task_migration_log(to_user_id);
CREATE INDEX IF NOT EXISTS idx_task_migration_at        ON public.task_migration_log(migrated_at DESC);

CREATE TABLE IF NOT EXISTS public.checklist_user_links (
  id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id             BIGINT      NOT NULL REFERENCES public.checklist(task_id) ON DELETE CASCADE,
  assignee_user_id    BIGINT      REFERENCES public.users(id)                ON DELETE SET NULL,
  created_by_user_id  BIGINT      REFERENCES public.users(id)                ON DELETE SET NULL,
  source_unique_id    BIGINT      REFERENCES public.unique_checklist(task_id) ON DELETE SET NULL,
  linked_at           TIMESTAMPTZ DEFAULT now(),
  UNIQUE (task_id)
);

CREATE INDEX IF NOT EXISTS idx_checklist_links_task_id  ON public.checklist_user_links(task_id);
CREATE INDEX IF NOT EXISTS idx_checklist_links_assignee ON public.checklist_user_links(assignee_user_id);
CREATE INDEX IF NOT EXISTS idx_checklist_links_creator  ON public.checklist_user_links(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_checklist_links_source   ON public.checklist_user_links(source_unique_id);

CREATE TABLE IF NOT EXISTS public.maintenance_user_links (
  id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id             BIGINT      NOT NULL REFERENCES public.machine_maintenance(task_id) ON DELETE CASCADE,
  assignee_user_id    BIGINT      REFERENCES public.users(id)                  ON DELETE SET NULL,
  created_by_user_id  BIGINT      REFERENCES public.users(id)                  ON DELETE SET NULL,
  source_unique_id    BIGINT      REFERENCES public.unique_maintanence(task_id) ON DELETE SET NULL,
  linked_at           TIMESTAMPTZ DEFAULT now(),
  UNIQUE (task_id)
);

CREATE INDEX IF NOT EXISTS idx_maintenance_links_task_id  ON public.maintenance_user_links(task_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_links_assignee ON public.maintenance_user_links(assignee_user_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_links_creator  ON public.maintenance_user_links(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_links_source   ON public.maintenance_user_links(source_unique_id);
